schema_version = "1.0.0"
id = "miunau_slcamera"
version = "1.0.1"
name = "Second Life-style camera"
tagline = "Second Life-style camera with ALT (option)/CTRL/SHIFT keys"
maintainer = "miunau"
type = "add-on"
website = "https://github.com/miunau/blender-secondlife-camera-addon"
tags = ["Camera"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]